#%RAML 1.0 DataType

properties:
  name:
    description: name of the person
  dateOfBirth:
    description: birth date
  age:
    description: age of a person
  address:
    description: permanent address
  tripStartDate:
    description: when your journey will start
  tripEndDate:
    description: when your journey will end
  planName:
  premium:
  coverage:
  purchaceDate:
  policyId:
    description: existing policy number
  newTripEndDate:
    description: when your journey will end
  additionalPremium:
    description: additional premium you have to pay
  extendDate:
    description: current date when customer extended the policy