#%RAML 1.0
title: travel-agent-sapi

/quote:
  description: get quote
  get:
    queryParameters:
      age:
        description: age of the person who is interested in Travel Insurance
        type: number
        minimum: 1
        maximum: 60
        example: 35
      destination:
        description: place where peron is willing to travel
        type: string
        example: "Asia"
        required: true
      tripStartDate:
        description: starting date of journey in yyyy-mm-dd format
        type: date-only
        required: true
        example: "2021-02-11"
      tripEndDate:
        description: ending date of journey in yyyy-mm-dd format
        type: date-only
        required: true
        example: "2021-02-21"
    responses:
      200:
        body:
          application/json:
            example: !include ./example/getQuoteResponse.json
              
   
        
    